### ISSUE TITLE
Contribute link currently does redirect accordingly

### ISSUE THREAD

**Issue by crnvl** [ConnysCode/cny_sh#7]
![image](https://github.com/ConnysCode/cny_sh/assets/40737538/8600d933-406d-48e0-9410-658442ec67a8)
The GitHub logo in the footer currently links to your GitHub profile directly instead of, at least what I'd expect it to do, redirect to the public repository.

**Comment by ConnysCode** [comment]
The contribute link is redirecting to the repo. The Icons are both redirecting to user profiles.

**Comment by crnvl** [comment]
Alright, that works then. Visually, this wasn't really clear to me though and it rather seemed like the Contribute text wasn't a link at all

**Comment by ConnysCode** [comment]
I will probably separate them with a bullet or something. I believe that'll fix the issue.
